name: Push to main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Print python version
        run: python --version
      - name: Install dependencies
        run: make install-dev
      - name: Test with pytest
        run: make test
